#![no_main]
#![no_std]

use core::mem::MaybeUninit;

use dsp::{AudioSample, BigFuckinBuffer};
use embassy_stm32::{bind_interrupts, peripherals};
use embedded as _; // global logger + panicking-behavior + memory layout

rtic_monotonics::systick_monotonic!(Mono, 1_000);

// Config options
/// Number of samples in a sample buffer
const BUFFER_SAMPLES: usize = 1024;
/// Number of sample buffers in the big ass global buffer of buffers
const NUM_BUFFERS: usize = 64;
/// Number of sample buffers to fit inside the DMA buffer
const DMA_BUFFER_SIZE_MULT: usize = 32;
/// Sample rate in Hz
const SAMPLE_RATE_U: u32 = 48000;
/// Example note frequency in Hz
const MIDDLE_C: f32 = 261.6256;

// Calculated based on config
const DMA_BUFFER_SIZE: usize = BUFFER_SAMPLES * DMA_BUFFER_SIZE_MULT;
const SAMPLE_RATE: f32 = SAMPLE_RATE_U as f32;

// There are somewhat confusingly 3 different types to represent a sample.
// The first is AudioSample (f32). This is what gets output by the DSP library.
// It is typically a floating point type.
// Next, is DacSample (i32). This is the type that the Dac is expecting.
// AudioSample is cast to DacSample at the end of the DSP chain.
// Finally is I2sSample (u32), which is the data type the i2s library uses.
// The DacSample gets unsafe reinterpreted as a u32 to satisfy the type restriction,
// but the data is still being sent represented as a DacSample, I just need to lie to the compiler.
/// Data type generated by DSP algorithms
//type AudioSample = f32; // NOTE: AudioSample was moved to dsp cause it makes sense, i promise
/// Data type to convert AudioSample to, is actually the type that gets sent over i2s
type DacSample = i32;
/// Data type to be sent over I2S
type I2sSample = u32;
type SampleBuffer = [DacSample; BUFFER_SAMPLES];
type DmaBuffer = [I2sSample; DMA_BUFFER_SIZE];

#[unsafe(link_section = ".axisram")]
static SHARED_DATA: MaybeUninit<embassy_stm32::SharedData> = MaybeUninit::uninit();
#[unsafe(link_section = ".axisram")]
static mut DMA_BUFFER: DmaBuffer = [0; DMA_BUFFER_SIZE];
#[unsafe(link_section = ".axisram")]
static mut BIG_FUCKIN_BUFFER: BigFuckinBuffer<BUFFER_SAMPLES, NUM_BUFFERS> =
    [[0f32; BUFFER_SAMPLES]; NUM_BUFFERS];

bind_interrupts!(struct Irqs {
    DMA1_STREAM0 => embassy_stm32::dma::InterruptHandler<peripherals::DMA1_CH0>;
});

#[rtic::app(
    device = embassy_stm32,
    dispatchers = [DFSDM1_FLT0, DFSDM1_FLT1, DFSDM1_FLT2, DFSDM1_FLT3],
    peripherals = true
)]
mod app {
    use dasp::Signal;
    use defmt::{debug, error, info, warn};
    use embassy_stm32::{self as hal, gpio, i2s, rcc, spi, time};
    use fugit::ExtU32;
    use rtic_monotonics::Monotonic;

    use super::*;
    use dsp::oscillators::{ConstHz, LinearPhase, Sine, Square};
    use dsp::{sine_oscillator, square_oscillator};

    // Shared resources go here
    #[shared]
    struct Shared {}

    // Local resources go here
    #[local]
    struct Local {
        osc: Sine,
        i2s2: i2s::I2S<'static, u32>,
    }

    #[init()]
    fn init(cx: init::Context) -> (Shared, Local) {
        info!("init");

        let cp = cx.core;

        let mut config = hal::Config::default();
        config.rcc.pll1 = Some(rcc::Pll {
            source: rcc::PllSource::HSI,    // 64 MHz -> DIVM1
            prediv: rcc::PllPreDiv::DIV4,   // DIVM1 = 4: 16 MHz -> DIVN1
            mul: rcc::PllMul::MUL60,        // DIVN1 = 60: 960 MHz -> DIVP1 + DIVQ1 + DIVR1
            divp: Some(rcc::PllDiv::DIV2),  // DIVP1 = 2: 480 MHz -> System clock + more
            divq: Some(rcc::PllDiv::DIV16), // DIVQ1 = 16: 60 MHz -> SPI1 + more
            divr: None,                     // Disabled
        });
        // Allow higher clock speed
        // (This isn't technically necessary since Scale0 is the default
        config.rcc.voltage_scale = rcc::VoltageScale::Scale0;
        // Set the system clock source to PLL1
        config.rcc.sys = rcc::Sysclk::PLL1_P;
        // Divide some peripheral prescalers to keep them within limits
        config.rcc.ahb_pre = rcc::AHBPrescaler::DIV2; // HPRE Prescaler
        config.rcc.apb1_pre = rcc::APBPrescaler::DIV2; // D2PRE1
        config.rcc.apb2_pre = rcc::APBPrescaler::DIV2; // D2PRE2
        config.rcc.apb3_pre = rcc::APBPrescaler::DIV2; // D1PRE
        config.rcc.apb4_pre = rcc::APBPrescaler::DIV2; // D3PRE
        config.rcc.supply_config = rcc::SupplyConfig::DirectSMPS; // THIS MAKES EVERYTHING WORK!

        debug!("Initializing HAL...");
        let p = hal::init_primary(config, &SHARED_DATA);
        debug!("HAL Initialized");

        // PB15 SPI2 I2S2_SDO
        // PB12 SPI2 I2S2_WS
        // PD3  SPI2 I2S2_CK
        let spi2 = p.SPI2;
        let i2s2_sdo = p.PB15;
        let i2s2_ws = p.PB12;
        let i2s2_ck = p.PD3;
        let i2s2_mck = p.PC6;
        let dma1_ch0 = p.DMA1_CH0;
        let mut i2s_config = i2s::Config::default();
        // I'm pretty sure this is audio frequency since the default is 48kHz
        // It would suck if this was bit frequency
        i2s_config.frequency = time::hz(SAMPLE_RATE_U);
        // I don't really know whats required for this, but this is the default
        // Hopefully my clock config can handle this
        i2s_config.gpio_speed = gpio::Speed::VeryHigh;
        // The MCU will be the device thats sending
        i2s_config.mode = i2s::Mode::Master;
        // PCM5102A in "standard i2s" mode is AKA "Philips" according to one guide I found
        // https://nodeloop.org/guides/i2s-interface-guide/
        i2s_config.standard = i2s::Standard::Philips;
        // The PCM5102A has 32 bit channels and might as well use all 32 of em
        i2s_config.format = i2s::Format::Data32Channel32;
        // idrk, this was the default
        i2s_config.clock_polarity = i2s::ClockPolarity::IdleLow;
        // The PCM5102A has an onboard clock that it will set based on the bit clock and lrck
        // TODO: I set this to true and connected the master clock when I was
        // troubleshooting the DMA issues. Set this back to false at some point and connect
        // the pin on the DAC to ground. Also will need to switch to new_txonly_nomck.
        i2s_config.master_clock = true;

        let dma_buf: &'static mut DmaBuffer = unsafe { &mut *core::ptr::addr_of_mut!(DMA_BUFFER) };
        // I DONT KNOW WHY BUT THIS MAKES DMA WORK
        // I thought I already initialized the array with zeros when I, you know,
        // initialized it with all zeros. But for some reason I need to do this too.
        dma_buf.fill(0);

        let i2s2 = i2s::I2S::new_txonly(
            spi2, i2s2_sdo, i2s2_ws, i2s2_ck, i2s2_mck, dma1_ch0, dma_buf, Irqs, i2s_config,
        );

        let mono_driver = Mono::start(cp.SYST, 480_000_000); // 480 MHz System Clock
        debug!("Monotonic Started");
        write_osc_to_i2s::spawn().unwrap();
        (
            Shared {},
            Local {
                osc: sine_oscillator(MIDDLE_C, SAMPLE_RATE),
                i2s2,
            },
        )
    }

    #[idle]
    fn idle(_: idle::Context) -> ! {
        info!("idle");

        loop {
            cortex_m::asm::nop();
        }
    }

    fn fill_buffer(buf: &mut SampleBuffer, osc: &mut impl Signal<Frame = AudioSample>) {
        fn f32_to_sample(s: AudioSample) -> DacSample {
            (s * DacSample::MAX as f32).clamp(DacSample::MIN as f32, DacSample::MAX as f32)
                as DacSample
        }
        buf.iter_mut().for_each(|s| *s = f32_to_sample(osc.next()));
    }

    fn fill_buffer_stereo(buf: &mut SampleBuffer, osc: &mut impl Signal<Frame = AudioSample>) {
        fn f32_to_sample(s: AudioSample) -> DacSample {
            (s * DacSample::MAX as f32).clamp(DacSample::MIN as f32, DacSample::MAX as f32)
                as DacSample
        }
        //buf.iter_mut().for_each(|s| *s = f32_to_sample(osc.next()));
        // This is a hacky solution to put a sample in the left and right channels
        for i in (0..buf.len()).step_by(2) {
            let next = f32_to_sample(osc.next());
            buf[i] = next;
            buf[i + 1] = next;
        }
    }

    #[task(local = [osc, i2s2, buf: SampleBuffer = [0; BUFFER_SAMPLES]], priority = 1)]
    async fn write_osc_to_i2s(mut cx: write_osc_to_i2s::Context) -> ! {
        info!("Starting write osc to i2s");
        let mut counter = 0u32;
        cx.local.i2s2.start();
        debug!("i2s2 Started");
        loop {
            fill_buffer_stereo(cx.local.buf, cx.local.osc);
            let to_send: &[u32] = unsafe {
                core::slice::from_raw_parts(cx.local.buf.as_ptr() as *const u32, cx.local.buf.len())
            };
            debug!("Filled buffer, {}", counter);
            debug!("{}", to_send[0]);
            cx.local
                .i2s2
                .write(&to_send)
                .await
                .inspect_err(|e| error!("Write error: {:?}", e));
            debug!("Sent buffer, {}", counter);
            counter += 1;
        }
    }
}
